project:
  type: website

format:
  html: 
    theme: pulse

website:
  title: "R Bootcamp"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Week 1: Basics"
        href: wk_01.html
      - text: "Week 2: dplyr"
        href: wk_02.html
      - text: "Week 3/4: readr & ggplot2"    
        href: wk_03.html
      # Add more weeks here as they are ready
