project:
  type: website

website:
  title: "R Bootcamp"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Week 1"
        href: wk_01.html
      # Add more weeks here as they are ready
